# Generated by Django 3.2.9 on 2021-11-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211103_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strongness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Strongness',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='strongness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.strongness'),
        ),
    ]
