# Generated by Django 3.2.9 on 2022-01-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211103_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strongness',
            name='name',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
