# Generated by Django 3.2.9 on 2022-01-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_strongness_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strongness',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
