# Generated by Django 3.2.9 on 2022-01-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_strongness_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
